### PR TITLE
NextUp playlist pipeline

### PR DESCRIPTION
**Pull request by lund5000**
- Implementation of the pipeline documented on the wiki: https://chirpradio.github.io/nextup/
- Brings functions and libraries up-to-date with latest versions
- Adds a bunch of tests

### CODE REVIEW

**Review by bmcdonn2 — APPROVED** [review]
Still getting my footing but tracing the logic as outlined in https://chirpradio.github.io/nextup/ and everything appears to be accounted for.

Only spot of confusion is how there's both an `update-playlist-storage` and `update-playlist-storage-v2` but I imagine long-term `-v2` will replace the original once everything flows through this pipeline?

**Comment by lund5000** [comment]
> Only spot of confusion is how there's both an `update-playlist-storage` and `update-playlist-storage-v2` but I imagine long-term `-v2` will replace the original once everything flows through this pipeline?

That's exactly right. The old one needs to stay in place while we're transitioning from the DJDB to NextUp, but eventually it could go away. After seeing you bump up against it and sleeping on it, I think there's a less gross way to achieve the same thing and eliminate the weird duplication. I'll work on that and tag you again when I've made the change.

**Comment by lund5000** [comment]
@bmcdonn2 Less-gross version committed that takes advantage of the fact that you can register multiple functions in the same index.js but deploy and run them separately. I refactored the current version that relies on the DJDB into [lib/updatePlaylistStorageFromDJDB.js](https://github.com/chirpradio/cloud-functions/blob/nextup-playlist-pipeline/update-playlist-storage/lib/updatePlaylistStorageFromDJDB.js), register both in [index.js](https://github.com/chirpradio/cloud-functions/blob/nextup-playlist-pipeline/update-playlist-storage/index.js), and setup separate start and deploy commands for them in package.json. This means no more weird "-v2" folder.

**Comment by bmcdonn2** [comment]
@lund5000 new approach looks good, makes a lot of sense to have them grouped under the same folder with distinct deploy commands.

Probably good to merge this now. What are we thinking in terms of performing the actual merge: the author merges after receiving approval or the reviewer does? This specific repo doesn't have any actions so I imagine it isn't a big deal who handles it but if we ever did setup some sort of automation we'd need to be mindful of the workflows.

**Pull request merged**
